### ISSUE TITLE
Absolute paths not working (with nuxtjs)

### ISSUE THREAD

**Issue by jonnyparris** [toddbluhm/env-cmd#33] opened 2018-01-31 16:00 UTC
Basically any path other than a local `.env-whatever` does not seem to work when using at runtime with `nuxt start` (just as my personal real life usecase). 
It would be awesome to use something like `/etc/my_project.conf.env` if possible?

Cheers

**Comment by toddbluhm** [comment] 2018-03-03 05:47
Yeah, thanks for bringing this up. I thought I had absolute pathing working, but apparently not. I will look into this.

**Comment by toddbluhm** [comment] 2018-03-03 06:16
Hey so I was just looking into this briefly, could you give me more specifics about this. I was just checking my test cases because I was sure I had this covered and I do have absolute paths covered, but maybe I am missing an edge case.

What OS are you using? (windows, mac, linux, solaris 😉)
What shell are you using? (bash, powershell, zsh, etc..)
What does the full `env-cmd` command look like that you are trying to use?
What does the command look like that you are executing on the shell prompt? `nuxt start`?

Hopefully, the answers to those questions will help me diagnose this further.

**Comment by jonnyparris** [comment] 2018-03-05 15:49
Heya,

Just reconfirmed locally using bash on ubuntu 16.04:
`node_modules/.bin/env-cmd /etc/testymctest.env yarn start` => variables do not load
`node_modules/.bin/env-cmd testymctest.env yarn start` => variables load as expected (such a great utitlity, thanks for sharing btw)

Setting the server port with `PORT=3333` in the env file is great for testing because you get instant feedback when nuxt starts as it prints ` OPEN  http://localhost:3333` when its parsed the variables successfully.

Hope that helps. I've already settled for using a local env file for now but this fix would be handy for future projects.

**Comment by toddbluhm** [comment] 2018-03-05 20:46
Thanks for the info, this helps a ton. I will try to get around to fixing it, this week and then release this upcoming the weekend.

**Comment by toddbluhm** [comment] 2018-03-21 06:06
@jonnyparris So i was just messing around with a similar setup on my mac and realized that the `/etc` folder files (atleast on mac) usually have more strict permissions than normal files. I was able to get absolute pathing working out of my `/etc` directory, but I had to make sure the permissions of the env file had the `r` (read) flag set for all of them (owner, group, others). Could you check your permissions and see if that is the issue?

**Comment by jonnyparris** [comment] 2018-03-29 14:05
sorry dude I'm not on that project anymore but absolute paths do seem to work on mac fwiw

**Comment by toddbluhm** [comment] 2018-04-22 09:06
So I finally found time to boot up my linux vm. Ran everything exactly as was stated `node_modules/.bin/env-cmd /etc/testymctest.env yarn start` using `PORT=3333` in the env file and it all worked great. It printed out `3333` from `process.env.PORT`.

At this point, I feel like I have spent enough time debugging this. I think the issue comes down to permissions and that the `/etc` folder files can have weird permissions sometimes. If someone can figure out an easily reproducible way to show this bug exists, I will be happy to revisit it.

@jonnyparris Thanks again for the bug report. I am sorry I was unable to reproduce it. Closing for now, but anyone is welcome to comment if they figure it out.

**Closed by toddbluhm** 2018-04-22 09:06 UTC
