### ISSUE TITLE
Not working in Windows 10: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by GorvGoyl** [toddbluhm/env-cmd#149] opened 2020-06-22 22:36 UTC
Issue: I''m not able to load any .env/.js file using `env-cmd`
How to reproduce:
1. install `npm install -g env-cmd`
2. create new folder and create `.env` file and paste below content (taken from example repo)
```
TEST_NAME=Default File Path Test
NODE_ENV=env-file
ENVVAR=exists
ENV_PATH=./.env
```

3. Run command `env-cmd` in that folder
This throws error which is mentioned below: 
```
PS C:\Users\1gour\OneDrive\Documents\old\Github\new> env-cmd
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.normalize (path.js:266:5)
    at parseNonShell (C:\Users\1gour\AppData\Roaming\nvm\v12.15.0\node_modules\env-cmd\node_modules\cross-spawn\lib\parse.js:49:31)
    at parse (C:\Users\1gour\AppData\Roaming\nvm\v12.15.0\node_modules\env-cmd\node_modules\cross-spawn\lib\parse.js:88:37)
    at Object.spawn (C:\Users\1gour\AppData\Roaming\nvm\v12.15.0\node_modules\env-cmd\node_modules\cross-spawn\index.js:9:20)
    at Object.EnvCmd (C:\Users\1gour\AppData\Roaming\nvm\v12.15.0\node_modules\env-cmd\dist\env-cmd.js:59:26)
    at async Object.CLI (C:\Users\1gour\AppData\Roaming\nvm\v12.15.0\node_modules\env-cmd\dist\env-cmd.js:19:16) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I tried to install it locally instead of globally but still same issue.

**Also, If I rename `.env` to anything else like `.env.dev` it denies its existence:**

```
PS C:\Users\1gour\OneDrive\Documents\old\Github\new> env-cmd -f .env.dev
Error: Failed to find .env file at default paths: [./.env,./.env.js,./.env.json]
    at getEnvFile (C:\Users\1gour\AppData\Roaming\nvm\v12.15.0\node_modules\env-cmd\dist\get-env-vars.js:58:11)
```
I've also tried using async file i.e. `async-env.js` but still same issue `Failed to find .env file `

I've tried uninstalling installing again but doesn't work. I'm not sure if somebody tested this package in Windows or not but I can't make it work!

Platform: Windows 10
Teminal: Powershell core 6.2.3 (also tried with cmd but same error)
"env-cmd": "^10.1.0",

**Comment by PerlBug** [comment] 2020-07-17 03:16
same problem

**Comment by bastiankoetsier** [comment] 2020-08-17 12:43
For me `-f/--file` is also throwing an error: 
```
env-cmd -f .env.development 

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
```

macOS Catalina
Running on Node `v14.0.0` with `env-cmd@10.0.1` 
The file exists in the same directory.

**Comment by rediska1114** [comment] 2020-08-19 12:08
@bastiankoetsier 

I have same error when I do not specify the executable file.

`env-cmd -f .env.development` throwing an error, but `env-cmd -f .env.development node sample.js` work ok

 macOS Catalina, Node v14.5.0, env-cmd@10.1.0

**Comment by masterprompt** [comment] 2020-08-30 21:25
Yeah, same here.  Looks like Catalina upgrade broke it.   Will have to dump env-cmd from the project now :-( was great while it lasted

macOS Catalina, Node v10.18.1, env-cmd@10.1.0

**Comment by mthomas46** [comment] 2020-10-01 21:11
Yep same, after spending about an hour setting up my project, can confirm that i am on macOS Catalina 10.15.7 Node 14.7.0

**Comment by aamir-gada** [comment] 2020-12-05 15:07
Did anyone find a fix for this?

**Comment by barder60** [comment] 2021-01-07 17:09
when you use env-cmd commands, you have to run env-cmd just before your app launch with your command.

**For windows** (trying to run build:dev):
- command line : `npm run build:dev`

my error was this code : 
```js
"scripts": {
    "start": "react-scripts start",
    "build": "set \"INLINE_RUNTIME_CHUNK=false\" && react-scripts build",
    "build:dev": "env-cmd -f \".env.development\" && set \"INLINE_RUNTIME_CHUNK=false\" &&  react-scripts build",
  }
  
```

solution : 
**package.json**
```json
"scripts": {
    "start": "react-scripts start",
    "build": "set \"INLINE_RUNTIME_CHUNK=false\" && react-scripts build",
    "build:dev": "set \"INLINE_RUNTIME_CHUNK=false\" && env-cmd -f \".env.development\" react-scripts build",
  }
```

(ignore on what does INLINE_RUNTIME_CHUNK that's just for the example)


.env.development
`
API_URL=http://something.com
`

.env
`
API_URL=http://otherthing.com
`

Now in your app you can do :

```js
const apiUrl = process.env.API_URL 
```

So if you call `npm run build` -> apiUrl will equal "http://otherthing.com" in your app
and if you call `npm run build:dev` -> apiUrl will equal "http://something.com" in your app

**Comment by tmclean15** [comment] 2021-04-29 12:22
I'm having the same issue, I've tried running on both MacOS Catalina 10.15.7 and Ubuntu 20.04. I've tried multiple different versions, including all versions from 9.0.0-10.1.0, with the same result:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at Object.spawn (child_process.js:551:13)
    at Object.spawn (/root/development/labnetic/node_modules/env-cmd/node_modules/cross-spawn/index.js:12:24)
    at Object.<anonymous> (/root/development/labnetic/node_modules/env-cmd/dist/env-cmd.js:57:30)
    at Generator.next (<anonymous>)
    at fulfilled (/root/development/labnetic/node_modules/env-cmd/dist/env-cmd.js:4:58) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Has this been looked into?

**Comment by ahartzog** [comment] 2021-09-04 10:12
Yeah can't get this working on Big Sur at all 🤷‍♂️

**Comment by ajbarry** [comment] 2021-11-06 03:59
I just wanted to chime in that in my case it was due to my use of end of line comments when documenting the purpose of the variables:

Bad:
```shell
# MY_VAR=foo # development
MY_VAR=bar # production
```

Good:
```shell
### development environment
# MY_VAR=foo
### production environment
MY_VAR=bar
```

Guess I expected `env-cmd` to parse like a shell.

Maybe others have invisibles or something trailing the variable values or CRLF is not supported? (I'm on OSX 11.6)
¯\\_(ツ)_/¯

**Comment by danielcn** [comment] 2022-02-02 11:26
I just did that without '&&' on macOS Monterey and it works fine for me:

```
"scripts": {
    "start": "env-cmd -f .env react-scripts start",
    "start:dev": "env-cmd -f .env-development react-scripts start",
    "build:staging": "sass src/styles/scss:src/styles/css && env-cmd -f .env-staging react-scripts build",
    "build:production": "sass src/styles/scss:src/styles/css && env-cmd -f .env-production react-scripts build",
    "test": "react-scripts test",
}

```
Also notice if you need to use '&&' try to use it before env-cmd command.

**Comment by kristijorgji** [comment] 2022-02-03 18:33
I can confirm this does not work env-cmd -f .env.test
.env.test exist still get error.

I also tried full path instead of realtive still does not work

**Comment by leqnam** [comment] 2022-02-25 10:31
without '&&' is working fine on Windows 11

**Comment by bbsimonbb** [comment] 2023-09-13 10:28
@leqnam, @danielcn and @barder60 have the solution. env-cmd requires a command. You can't just run it on its own. If you do, you get the error in the title of this issue... "The "path" argument must be of type string. Received type undefined".

**Closed** 2024-12-11 07:37 UTC
