### ISSUE TITLE
Allow usage of mixed file types

### ISSUE THREAD

**Issue by GuillaumeHumbert** [toddbluhm/env-cmd#37] opened 2018-03-28 15:56 UTC
It would be great to be able to use env variable sources of multiple types, _e.g._ pull some variables from the `.env-cmdrc` file as well as a `.env.local` file.

The use case for this would be for instance to have a cleanly-defined `.env-cmdrc` with all "regular" environments (development, test, staging, production...) containing non-sensible data that could be committed, along with a `.env.local` file that would stay uncommitted, where some passwords, tokens or security-related stuff would be put, mainly for development purposes (in production, those variables could be replaced by hidden variables outside of the project's scope).

The syntax could be quite similar to the existing one to import multiple environment groups from an rc file, like this : `env-cmd development,./.env.local ...`. The problem today is you can't do that, it seems from the moment you have a rc file in your repo it will not try to resolve the provided env filename to something else than a root property in the rc file. Indeed with the syntax I just provided, the `.env.local` file seems to be completely ignored, and if used exclusively without the `development` environment, it spawns the following error : 
```
Error: could not find environment:
    .env.local
  in .rc file
```

It is possible to use a JS file export instead of the rc file, in which we import from a non-committed JS file the sensible data and destructure it in the targeted environment's object property. But IMHO it is less clean and less expressive than properly declaring that you expect a local env file to be provided for some scripts like _start_ or _inspect_ for instance. It is also visually more cluttered since instead of a simple `env-cmd development` command, you have something like `env-cmd ./.env.development.js`. For reference, this is what I currently did:
```javascript
// ./.env.development.js
const localEnv = require('./.env.local');

module.exports = {
  FOO: 'foo',
  BAR: 'bar',
  ...localEnv,
};
```
```javascript
// ./.env.local.js
module.exports = {
  FOO: 'override-foo',
  SUPER_SECRET_TOKEN: 'xyz',
};
```

Do you think this would be useful? Is my approach regarding the JS file correct? How would you do to combine several environments with some of them being committed and not others (I'm really talking about combining them, not duplicating the whole _development_ environment in a `.env.local` file and using that for local dev scripts) without requiring to JS file configs?

Thanks 🙂

**Comment by toddbluhm** [comment] 2018-04-16 23:28
Hey @GuillaumeHumbert,

Thanks for the question and input!

First, I would like to say that yes your usage for the `.js` file is correct.

Now on to your main question. I personally feel that combining them would be bad and somewhat overly complex. I hear what you are saying about committing non-sensitive data and in fact, I actually do that myself.

To clear things up, how I use this lib is simple. I create two `.rc` files. One is the normal `.env-cmdrc` that contains all env vars + sensitive vars. The other one is called `.env-cmdrc-example`. This file is a duplicate of `.env-cmdrc` except that I don't include the sensitive values (the keys remain in the file, just with an empty string value). I commit the `.env-cmdrc-example` file and keep the real `.env-cmdrc` file in my `.gitignore`. 

Then when a new person comes on the project, they just pull down the repo and duplicate the `.env-cmdrc-example` file to `.env-cmdrc`. Now they have all the correctly spelled environment variables input for them with the correct values and the only thing they have to do is input their personal sensitive data.

While this approach may not be perfectly DRY, I find it prevents mistakes in missing to define env vars or misspelling env vars. It also helps newcomers to the project know exactly all that needs to be defined for a project to run in any environment. I guess I just don't like splitting up my env vars. I like to see them all defined in one spot. That is definitely a personal preference though.

Having said all of that and putting aside my personal preference, I still don't like the idea of mixing a `.env` file with a `.rc` file.

But as I have said on many other support tickets, I am certainly willing to reconsider my stance. If enough people want it, then I certainly will reconsider adding it. I will leave this open for a while to allow others to see it and add their support if they like.

**Comment by toddbluhm** [comment] 2018-09-05 17:55
I re-read this again and honestly my position is still the same. I don't see any additional support from others asking for it either. Closing for now.

**Closed by toddbluhm** 2018-09-05 17:55 UTC
